#include "PfcApp.h"
#include "Moose.h"
#include "AppFactory.h"

template<>
InputParameters validParams<PfcApp>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  return params;
}

PfcApp::PfcApp(const std::string & name, InputParameters parameters) :
    MooseApp(name, parameters)
{
  srand(processor_id());

  Moose::registerObjects(_factory);
  PfcApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  PfcApp::associateSyntax(_syntax, _action_factory);
}

PfcApp::~PfcApp()
{
}

// External entry point for dynamic application loading
extern "C" void PfcApp__registerApps() { PfcApp::registerApps(); }
void
PfcApp::registerApps()
{
  registerApp(PfcApp);
}

// External entry point for dynamic object registration
extern "C" void PfcApp__registerObjects(Factory & factory) { PfcApp::registerObjects(factory); }
void
PfcApp::registerObjects(Factory & factory)
{
}

// External entry point for dynamic syntax association
extern "C" void PfcApp__associateSyntax(Syntax & syntax, ActionFactory & action_factory) { PfcApp::associateSyntax(syntax, action_factory); }
void
PfcApp::associateSyntax(Syntax & syntax, ActionFactory & action_factory)
{
}
